Add early stop to autoencoder
nv-morpheus/dfencoder pull request #2
Opened 2022-09-14 15:20 UTC by efajardo-nv

PR from @gbatmaz originally targeting https://github.com/efajardo-nv/dfencoder/tree/morpheus-22.08.

2022-11-16 03:57 UTC, mdemoret-nv requested changes
Couple of small changes

2022-11-16 03:57 UTC, mdemoret-nv commented on dfencoder/autoencoder.py
> +    def fit(self, df, epochs=1, val=None, patience=5):
Is `patience` something that will change for every call to `fit`? If not, we should be leaving the signature of `fit()` alone and change this to a contstructor arg.

2022-11-16 03:57 UTC, mdemoret-nv commented on dfencoder/autoencoder.py
> +                            print('Early stopping: early stop count({}) >= patience({})'.format(count_es, patience))
This needs to be surrounded by `if self.verbose`

2022-11-16 16:10 UTC, efajardo-nv commented on dfencoder/autoencoder.py
> +    def fit(self, df, epochs=1, val=None, patience=5):
@mdemoret-nv discussed this with @gbatmaz. we'll move it to constructor to be more consistent with other training parameters like learning rate.

2022-11-16 16:38 UTC, efajardo-nv commented
updates from feedback made. ready for re-review

2022-11-16 17:09 UTC, mdemoret-nv approved these changes

2022-11-16 17:10 UTC, mdemoret-nv commented
@efajardo-nv Can you resolve the merge conflicts and then we can merge?

2022-11-16 17:46 UTC, gbatmaz approved these changes
LGTM

2023-01-26 19:52 UTC, mdemoret-nv approved these changes

2023-01-26 22:10 UTC, gbatmaz approved these changes
LGTM

2023-01-27 00:18 UTC, mdemoret-nv commented
/merge

2023-01-27 00:18 UTC, merged